# Generated by cli/homebrew-formula.mjs in the AstraCode repository.
# Edit that, not this: ops/publish-cli.sh rewrites this file on every release.
class AstracodeAgent < Formula
  desc "AstraCode's coding agent, headless: run one task from a shell, CI job or script"
  homepage "https://astracode.io"
  version "0.3.0"

  livecheck do
    url "https://astracode.io/downloads/cli/latest"
    regex(/^v?(\d+(?:\.\d+)+(?:-[0-9A-Za-z.]+)?)$/i)
  end

  on_macos do
    on_arm do
      url "https://astracode.io/downloads/cli/0.3.0/astracode-agent-0.3.0-darwin-arm64.tar.gz"
      sha256 "d84a8b3817272f2987b2e6a544cf1b312f43fa35eae76a7d758c4e8cb5b3239e"
    end
    on_intel do
      url "https://astracode.io/downloads/cli/0.3.0/astracode-agent-0.3.0-darwin-x64.tar.gz"
      sha256 "8884ba2eb1986006690991fd7327ec6bba5bec5acb148f03dde320a160638794"
    end
  end

  on_linux do
    on_arm do
      url "https://astracode.io/downloads/cli/0.3.0/astracode-agent-0.3.0-linux-arm64.tar.gz"
      sha256 "0abad593b7d33dc6a76e1af4db3ee0f077dd40e0bf0cd0d46bc806794a3cb7be"
    end
    on_intel do
      url "https://astracode.io/downloads/cli/0.3.0/astracode-agent-0.3.0-linux-x64.tar.gz"
      sha256 "0e88a499cd3dc8f556c43162a807c3d652b2874816bcba03aab77ea16f885737"
    end
  end

  def install
    bin.install "astracode-agent"
  end

  test do
    assert_equal "astracode-agent #{version}", shell_output("#{bin}/astracode-agent --version").strip
  end
end
