# Generated by cli/homebrew-formula.mjs in the AstraCode repository.
# Edit that, not this: ops/publish-cli.sh rewrites this file on every release.
class AstracodeAgent < Formula
  desc "AstraCode's coding agent, headless: run one task from a shell, CI job or script"
  homepage "https://astracode.io"
  version "0.4.0"

  livecheck do
    url "https://astracode.io/downloads/cli/latest"
    regex(/^v?(\d+(?:\.\d+)+(?:-[0-9A-Za-z.]+)?)$/i)
  end

  on_macos do
    on_arm do
      url "https://astracode.io/downloads/cli/0.4.0/astracode-agent-0.4.0-darwin-arm64.tar.gz"
      sha256 "41c8c9284578c8d56802e23d5f3dbba15783c9ee4df7cb359e296c68a44e9765"
    end
    on_intel do
      url "https://astracode.io/downloads/cli/0.4.0/astracode-agent-0.4.0-darwin-x64.tar.gz"
      sha256 "321e8b63a672f429df1e262e8fe595f21cccd6d0dd7af25b84a7c313e33b05bf"
    end
  end

  on_linux do
    on_arm do
      url "https://astracode.io/downloads/cli/0.4.0/astracode-agent-0.4.0-linux-arm64.tar.gz"
      sha256 "7162c837c62a5ef5321a1dd64f85338e105180bdd327de46b01c1244f2263b64"
    end
    on_intel do
      url "https://astracode.io/downloads/cli/0.4.0/astracode-agent-0.4.0-linux-x64.tar.gz"
      sha256 "55ec47ab8ca5d699b194403a8abc22b6de620390479d0098be612f47c0a57bc0"
    end
  end

  def install
    bin.install "astracode-agent"
  end

  test do
    assert_equal "astracode-agent #{version}", shell_output("#{bin}/astracode-agent --version").strip
  end
end
