# Generated by cli/homebrew-formula.mjs in the AstraCode repository.
# Edit that, not this: ops/publish-cli.sh rewrites this file on every release.
class AstracodeAgent < Formula
  desc "AstraCode's coding agent, headless: run one task from a shell, CI job or script"
  homepage "https://astracode.io"
  version "0.4.1"

  livecheck do
    url "https://astracode.io/downloads/cli/latest"
    regex(/^v?(\d+(?:\.\d+)+(?:-[0-9A-Za-z.]+)?)$/i)
  end

  on_macos do
    on_arm do
      url "https://astracode.io/downloads/cli/0.4.1/astracode-agent-0.4.1-darwin-arm64.tar.gz"
      sha256 "8a056ad24f4b1a8735b9686d53b6d6dcce5cbb76a0e6fe2540b93a5f3ce0d403"
    end
    on_intel do
      url "https://astracode.io/downloads/cli/0.4.1/astracode-agent-0.4.1-darwin-x64.tar.gz"
      sha256 "e63e8d782eae82eeb021a330d4d81a1a506e0e9574380aa96fc895180b1269bb"
    end
  end

  on_linux do
    on_arm do
      url "https://astracode.io/downloads/cli/0.4.1/astracode-agent-0.4.1-linux-arm64.tar.gz"
      sha256 "0bcd50def50f397800d57b302b78dc6fcd4261d72da9455ec7ecdbe36dc1e3c1"
    end
    on_intel do
      url "https://astracode.io/downloads/cli/0.4.1/astracode-agent-0.4.1-linux-x64.tar.gz"
      sha256 "30389ed6ad1225889ee3b1042594d42b4dc59146170612a72d35c23ab3388192"
    end
  end

  def install
    bin.install "astracode-agent"
  end

  test do
    assert_equal "astracode-agent #{version}", shell_output("#{bin}/astracode-agent --version").strip
  end
end
